### ISSUE TITLE
Incompatible dependencies for scikit-learn and numpy?

### ISSUE THREAD

**Issue by nballenger** [CartoDB/crankshaft#213]
I'm getting a failure during `make install` while it attempts to build the wheel for scikit-learn:

```
Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-oOHLvU/scikit-learn/setup.py", line 247, in <module>
      setup_package()
    File "/tmp/pip-build-oOHLvU/scikit-learn/setup.py", line 227, in setup_package
      .format(numpy_req_str, instructions))
  ImportError: Numerical Python (NumPy) is not installed.
  scikit-learn requires NumPy >= 1.6.1.
```

In the requirements and setup files you've got scikit-learn pinned at 0.17 and numpy pinned at 1.11. At that rev scikit-learn requires numpy 1.6.1: 

https://github.com/scikit-learn/scikit-learn/blob/da4f480a6adf5fed30a42500fe0e5a21c404ac2a/setup.py#L119

@Algunenano, looks like this is from your commit 54646ac, where you rolled the numpy version back from 1.6.1 to 1.11.0. Is there any reason numpy shouldn't be at 1.6.1 to match the scikit-learn dependency?

Thanks, Nick

**Comment by nballenger** [comment]
Whoops, my brain made 1.6.1 a higher version than 1.11.0. Versioning isn't the problem, may be a completely transient issue. I'll reopen if it recurs.
